// Mocks generated by Mockito 5.1.0 from annotations
// in twitter_flutter/test/repositories/authentication/auth_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:twitter_flutter/utils/Web Services/edit_profile/update_password_request.dart'
as _i2;

import '../../blocs/UpdatePasswordStates/updatepassword_bloc_test.mocks.dart';

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [AuthenticationRequests].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdatePasswordRequest extends _i1.Mock
    implements _i2.UpdatePasswordRequests {
  MockUpdatePasswordRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> UpdatePassword({dynamic oldPassword, dynamic newPassword}) =>
      (super.noSuchMethod(
          Invocation.method(
              #UpdatePassword, [], {#oldPassword: oldPassword, #password: newPassword}),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
}
