// Mocks generated by Mockito 5.1.0 from annotations
// in twitter_flutter/test/blocs/UpdatePasswordStates/updatepassword_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:twitter_flutter/utils/Web%20Services/edit_profile/update_password_request.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [UpdatePasswordRequests].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdatePasswordRequests extends _i1.Mock
    implements _i2.UpdatePasswordRequests {
  MockUpdatePasswordRequests() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> UpdatePassword(
          {dynamic New_Password, dynamic Old_Password, dynamic token}) =>
      (super.noSuchMethod(
          Invocation.method(#UpadtePassword, [], {
            #New_Password: New_Password,
            #Old_Password: Old_Password,
            #token: token
          }),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
}
