// Mocks generated by Mockito 5.1.0 from annotations
// in twitter_flutter/test/repositories/authentication/auth_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:twitter_flutter/utils/Web%20Services/authentication/authentication_requests.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [AuthenticationRequests].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRequests extends _i1.Mock
    implements _i2.AuthenticationRequests {
  MockAuthenticationRequests() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> Login({dynamic username, dynamic password}) =>
      (super.noSuchMethod(
          Invocation.method(
              #Login, [], {#username: username, #password: password}),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
  @override
  _i3.Future<String> signUp(
          {dynamic name,
          dynamic email,
          dynamic username,
          dynamic gender,
          dynamic password,
          dynamic birth_date}) =>
      (super.noSuchMethod(
          Invocation.method(#signUp, [], {
            #name: name,
            #email: email,
            #username: username,
            #gender: gender,
            #password: password,
            #date_of_birth: birth_date
          }),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
}
