// Mocks generated by Mockito 5.1.0 from annotations
// in twitter_flutter/test/blocs/LoginStates/login_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:twitter_flutter/models/authentication/user_authentication_model.dart'
    as _i3;
import 'package:twitter_flutter/repositories/authentication/auth_repository.dart'
    as _i4;
import 'package:twitter_flutter/utils/Web%20Services/authentication/authentication_requests.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAuthenticationRequests_0 extends _i1.Fake
    implements _i2.AuthenticationRequests {}

class _FakeUserAuthenticationModel_1 extends _i1.Fake
    implements _i3.UserAuthenticationModel {}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthenticationRequests get authReq =>
      (super.noSuchMethod(Invocation.getter(#authReq),
              returnValue: _FakeAuthenticationRequests_0())
          as _i2.AuthenticationRequests);
  @override
  set authReq(_i2.AuthenticationRequests? _authReq) =>
      super.noSuchMethod(Invocation.setter(#authReq, _authReq),
          returnValueForMissingStub: null);
  @override
  _i5.Future<_i3.UserAuthenticationModel> login(
          {dynamic username, dynamic password}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #login, [], {#username: username, #password: password}),
              returnValue: Future<_i3.UserAuthenticationModel>.value(
                  _FakeUserAuthenticationModel_1()))
          as _i5.Future<_i3.UserAuthenticationModel>);
  @override
  _i5.Future<_i3.UserAuthenticationModel> signUp(
          {dynamic name,
          dynamic password,
          dynamic email,
          dynamic date_of_birth,
          dynamic gender,
          dynamic username}) =>
      (super.noSuchMethod(
              Invocation.method(#signUp, [], {
                #name: name,
                #password: password,
                #email: email,
                #date_of_birth: date_of_birth,
                #gender: gender,
                #username: username
              }),
              returnValue: Future<_i3.UserAuthenticationModel>.value(
                  _FakeUserAuthenticationModel_1()))
          as _i5.Future<_i3.UserAuthenticationModel>);
  @override
  _i5.Future<_i3.UserAuthenticationModel> verification(
          {dynamic id, dynamic verification_code}) =>
      (super.noSuchMethod(
              Invocation.method(#verification, [],
                  {#id: id, #verification_code: verification_code}),
              returnValue: Future<_i3.UserAuthenticationModel>.value(
                  _FakeUserAuthenticationModel_1()))
          as _i5.Future<_i3.UserAuthenticationModel>);
}

/// A class which mocks [AuthenticationRequests].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRequests extends _i1.Mock
    implements _i2.AuthenticationRequests {
  MockAuthenticationRequests() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> Login({dynamic username, dynamic password}) =>
      (super.noSuchMethod(
          Invocation.method(
              #Login, [], {#username: username, #password: password}),
          returnValue: Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<String> signUp(
          {dynamic name,
          dynamic email,
          dynamic username,
          dynamic gender,
          dynamic password,
          dynamic birth_date}) =>
      (super.noSuchMethod(
          Invocation.method(#signUp, [], {
            #name: name,
            #email: email,
            #username: username,
            #gender: gender,
            #password: password,
            #birth_date: birth_date
          }),
          returnValue: Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<String> Verification({dynamic id, dynamic verification_code}) =>
      (super.noSuchMethod(
          Invocation.method(#Verification, [],
              {#id: id, #verification_code: verification_code}),
          returnValue: Future<String>.value('')) as _i5.Future<String>);
}
