// Mocks generated by Mockito 5.1.0 from annotations
// in twitter_flutter/test/blocs/LoginStates/login_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:twitter_flutter/models/authentication/user_authentication_model.dart'
    as _i3;
import 'package:twitter_flutter/models/objects/user.dart' as _i4;
import 'package:twitter_flutter/repositories/user_management_repository.dart'
    as _i5;
import 'package:twitter_flutter/utils/Web%20Services/user_management_requests.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUserManagementRequests_0 extends _i1.Fake
    implements _i2.UserManagementRequests {}

class _FakeUserAuthenticationModel_1 extends _i1.Fake
    implements _i3.UserAuthenticationModel {}

class _FakeUserModel_2 extends _i1.Fake implements _i4.UserModel {}

/// A class which mocks [UserManagementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserManagementRepository extends _i1.Mock
    implements _i5.UserManagementRepository {
  MockUserManagementRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserManagementRequests get userManagementRequests =>
      (super.noSuchMethod(Invocation.getter(#userManagementRequests),
              returnValue: _FakeUserManagementRequests_0())
          as _i2.UserManagementRequests);
  @override
  set userManagementRequests(
          _i2.UserManagementRequests? _userManagementRequests) =>
      super.noSuchMethod(
          Invocation.setter(#userManagementRequests, _userManagementRequests),
          returnValueForMissingStub: null);
  @override
  _i6.Future<_i3.UserAuthenticationModel> login(
          {dynamic username, dynamic password}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #login, [], {#username: username, #password: password}),
              returnValue: Future<_i3.UserAuthenticationModel>.value(
                  _FakeUserAuthenticationModel_1()))
          as _i6.Future<_i3.UserAuthenticationModel>);
  @override
  _i6.Future<_i3.UserAuthenticationModel> signUp(
          {dynamic name,
          dynamic password,
          dynamic email,
          dynamic date_of_birth,
          dynamic gender,
          dynamic username}) =>
      (super.noSuchMethod(
              Invocation.method(#signUp, [], {
                #name: name,
                #password: password,
                #email: email,
                #date_of_birth: date_of_birth,
                #gender: gender,
                #username: username
              }),
              returnValue: Future<_i3.UserAuthenticationModel>.value(
                  _FakeUserAuthenticationModel_1()))
          as _i6.Future<_i3.UserAuthenticationModel>);
  @override
  _i6.Future<_i3.UserAuthenticationModel> verify(
          {dynamic email_or_username, dynamic verificationCode}) =>
      (super.noSuchMethod(
              Invocation.method(#verify, [], {
                #email_or_username: email_or_username,
                #verificationCode: verificationCode
              }),
              returnValue: Future<_i3.UserAuthenticationModel>.value(
                  _FakeUserAuthenticationModel_1()))
          as _i6.Future<_i3.UserAuthenticationModel>);
  @override
  _i6.Future<String> updatePassword(
          {dynamic New_Password, dynamic Old_Password}) =>
      (super.noSuchMethod(
          Invocation.method(#updatePassword, [],
              {#New_Password: New_Password, #Old_Password: Old_Password}),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<_i4.UserModel> editProfile() =>
      (super.noSuchMethod(Invocation.method(#editProfile, []),
              returnValue: Future<_i4.UserModel>.value(_FakeUserModel_2()))
          as _i6.Future<_i4.UserModel>);
  @override
  _i6.Future<_i4.UserModel> getUserProfile(
          {dynamic username, dynamic access_token}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserProfile, [],
                  {#username: username, #access_token: access_token}),
              returnValue: Future<_i4.UserModel>.value(_FakeUserModel_2()))
          as _i6.Future<_i4.UserModel>);
}

/// A class which mocks [UserManagementRequests].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserManagementRequests extends _i1.Mock
    implements _i2.UserManagementRequests {
  MockUserManagementRequests() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> login({dynamic username, dynamic password}) =>
      (super.noSuchMethod(
          Invocation.method(
              #login, [], {#username: username, #password: password}),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<String> signUp(
          {dynamic name,
          dynamic email,
          dynamic username,
          dynamic gender,
          dynamic password,
          dynamic birth_date}) =>
      (super.noSuchMethod(
          Invocation.method(#signUp, [], {
            #name: name,
            #email: email,
            #username: username,
            #gender: gender,
            #password: password,
            #birth_date: birth_date
          }),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<String> Verification(
          {dynamic email_or_username, dynamic verificationCode}) =>
      (super.noSuchMethod(
          Invocation.method(#Verification, [], {
            #email_or_username: email_or_username,
            #verificationCode: verificationCode
          }),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<String> UpdatePassword(
          {dynamic New_Password, dynamic Old_Password}) =>
      (super.noSuchMethod(
          Invocation.method(#UpdatePassword, [],
              {#New_Password: New_Password, #Old_Password: Old_Password}),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<String> editProfile(
          {dynamic Name,
          dynamic Location,
          dynamic Website,
          dynamic Bio,
          dynamic Month_Day_Access,
          dynamic Year_Access,
          dynamic Birth_Date}) =>
      (super.noSuchMethod(
          Invocation.method(#editProfile, [], {
            #Name: Name,
            #Location: Location,
            #Website: Website,
            #Bio: Bio,
            #Month_Day_Access: Month_Day_Access,
            #Year_Access: Year_Access,
            #Birth_Date: Birth_Date
          }),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<String> getUserProfile({String? access_token, String? username}) =>
      (super.noSuchMethod(
          Invocation.method(#getUserProfile, [],
              {#access_token: access_token, #username: username}),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
}
